const phoneBill = {
  id: 1,
  price: 1233,
  date: "2018-06-08T04:00:00.000Z",
  createdAt: "2018-05-14T21:06:28.313Z",
  updatedAt: "2018-05-14T21:06:28.313Z",
  userId: 1
};

const rentBill = {
  id: 1,
  price: 1223,
  date: "2018-06-01T04:00:00.000Z",
  createdAt: "2018-05-14T21:06:28.313Z",
  updatedAt: "2018-05-14T21:06:28.313Z",
  userId: 1
};

const demoAccounts = {
  error: false,
  accountInfo: [
    {
      account_id: "BJwax5vY6kFww0qQ9aJ9C4LnJab5zkf9qkYaP",
      balances: { available: 995.88, current: 995.88, limit: null },
      mask: "1371",
      name: "CHASE SAVINGS",
      official_name: null,
      subtype: "savings",
      type: "depository"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      balances: { available: 2115.25, current: 995.88, limit: null },
      mask: "6254",
      name: "CHASE COLLEGE",
      official_name: null,
      subtype: "checking",
      type: "depository"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      balances: { available: 925.21, current: 9074.79, limit: 10000 },
      mask: "8623",
      name: "CREDIT CARD",
      official_name: "FREEDOM UNLIMITED CREDIT CARD",
      subtype: "credit card",
      type: "credit"
    }
  ]
};

const demoTransaction = {
  error: false,
  transaction: [
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 68.79,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-05-02",
      location: [Object],
      name: "ALIADA",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "J93g1V87NLc337LYbwqbCNpazZBrA7tbopwVr",
      transaction_type: "place"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 6.22,
      category: ["Food and Drink", "Restaurants"],
      category_id: "22006001",
      date: "2018-05-02",
      location: [Object],
      name: "Lyft",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "QnjYkV9yOxUjjJm9P5vPTaP9ZQo3k4uEDjmeB",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 12.09,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-05-02",
      location: [Object],
      name: "Potbelly Sandwich Shop",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "avMYdpkrPAFMMmZOneBnCN6moRLZr7tZYeXpE",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 5,
      category: ["Food and Drink", "Restaurants"],
      category_id: "12015003",
      date: "2018-05-02",
      location: [Object],
      name: "QueensJS",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "xpA3re65Rgf11VxnaXMaFp57XLZV3MCMrvz30",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 26.9,
      category: ["Food and Drink", "Restaurants"],
      category_id: "19047000",
      date: "2018-05-01",
      location: [Object],
      name: "FOOD BAZAAR",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "4q91nydP0wc88Rb604q0H6p8PAvq74CkNQb6B",
      transaction_type: "place"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: -2000,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-04-30",
      location: [Object],
      name:
        "BOOK TRANSFER CREDIT B/O: WOORI BANK CHUNG KU SEOUL KOREA REP. SOUTH 100 ORG:/010097743 PARK HYE SUK REF: TEL:6466591495/BNF/CHASE BANK 39-01 MAIN STREET, FLUSHING, NY. CHASE TRN: 8953100120GS",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "RprYAEV7mOfrr3yzeApeIjZDz6xg0qtyQRD5Y",
      transaction_type: "place"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 15,
      category: ["Food and Drink", "Restaurants"],
      category_id: "10005000",
      date: "2018-04-30",
      location: [Object],
      name: "INTERNATIONAL INCOMING WIRE FEE",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "E5D8dgrXBkHDD1xZEB6EsXM756ajJntpkaBvM",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 4.75,
      category: ["Food and Drink", "Restaurants"],
      category_id: "19025000",
      date: "2018-04-30",
      location: [Object],
      name: "LA COLOMBE - PRINCE",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "jZYz3mJR8MILL9PBzMrzCz7PrgyakDIROXNMn",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 7.25,
      category: ["Food and Drink", "Restaurants"],
      category_id: "21010003",
      date: "2018-04-30",
      location: [Object],
      name: "POMMES FRITES",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "0LownP96ZgH44v6kMnLMhqzLVeRJb6fr8aNEq",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 29.92,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-04-30",
      location: [Object],
      name: "SEAMLSSMOKJAKOREANEAT",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "rOqLre956EcrrBQP9gM9Im7QeJnkLBIBE8m5k",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 7,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-04-29",
      location: [Object],
      name: "JUSTINO`S PIZZERIA",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "vQKqgedkRPsppPQ67DM7IP9XDBKrqmFmNj3J4",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 11.97,
      category: ["Travel", "Car Service", "Ride Share"],
      category_id: "13005000",
      date: "2018-04-29",
      location: [Object],
      name: "LENWICH 10 HANOVER LLC",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "Axd48ZAnvJfddg6vkexkcqp3XNBdynf6g0q5y",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 73.33,
      category: ["Travel", "Car Service", "Ride Share"],
      category_id: "19047000",
      date: "2018-04-27",
      location: [Object],
      name: "H MART",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "k5dYye8RrNH00Yqd9g49TPqQxeLypRFRwB715",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 10,
      category: ["Travel", "Car Service", "Ride Share"],
      category_id: "12018004",
      date: "2018-04-27",
      location: [Object],
      name: "UNITY",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "KVy7PXZMDxUyyEQgd5pdHA5YdV07BmsQY7RJr",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 12.83,
      category: ["Travel", "Car Service", "Ride Share"],
      category_id: "13005000",
      date: "2018-04-26",
      location: [Object],
      name: "Subway",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "ydvy4eL5m0I11oJx6jM6FqKvxLmbyOfO1xNY4",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: -294.6,
      category: ["Travel", "Car Service", "Ride Share"],
      category_id: "21005000",
      date: "2018-04-24",
      location: [Object],
      name: "Payment Thank You-Mobile",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "3P7Dn3M1gdUJJ48bzBPzF1kPEzYL9DSKZBpdp",
      transaction_type: "special"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 294.6,
      category: ["Food and Drink", "Restaurants"],
      category_id: "16001000",
      date: "2018-04-24",
      location: [Object],
      name: "Payment to Chase card ending in 8623 04/24",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "MMkVBYm95xukkOwv6Qy6IzKaJw84bpIMeV3qz",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 5.54,
      category: ["Food and Drink", "Restaurants"],
      category_id: "19043000",
      date: "2018-04-22",
      location: [Object],
      name: "Duane Reade",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "BJwax5vY6kFww0qQ9aJ9C4LJgjYmA7f9qkY5o",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 44.6,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-04-22",
      location: [Object],
      name: "KONDO RESTAURANT",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "1Db6nqVLAgUaa05QM1DMC7Z8JbDAgXumB8pDv",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 29.94,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-04-22",
      location: [Object],
      name: "OBAO",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "qVP6re7OaqU117QvYKMYFvz8Oajg6JtJZvV4j",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 9.45,
      category: [
        "Community",
        "Organizations and Associations",
        "Charities and Non-Profits"
      ],
      category_id: "19043000",
      date: "2018-04-22",
      location: [Object],
      name: "Rite Aid",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "PQ0YKV7ExXs00KaeQBAQTEq63xpvjAFmQ3ejz",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 9.8,
      category: [
        "Community",
        "Organizations and Associations",
        "Charities and Non-Profits"
      ],
      category_id: "13005000",
      date: "2018-04-19",
      location: [Object],
      name: "KING OF FALAFEL & SHA",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "LOK9qV571xcKKYLow7pwHVKNr6RD3BF0K4e7b",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 6.39,
      category: [
        "Community",
        "Organizations and Associations",
        "Charities and Non-Profits"
      ],
      category_id: "13005000",
      date: "2018-04-19",
      location: [Object],
      name: "OPEN KITCHEN 15 IN",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "DZLJxbj5EmILLQbvqDwqCmJa6Y4jERIZv3Dd4",
      transaction_type: "place"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 10,
      category: [
        "Community",
        "Organizations and Associations",
        "Charities and Non-Profits"
      ],
      category_id: "21010001",
      date: "2018-04-19",
      location: [Object],
      name: "Venmo",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "ORvYyVgZbPtvvQaNMmkMC9OND7ELqgI8a3KDO",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 28.04,
      category: ["Shops", "Supermarkets and Groceries"],
      category_id: "19047000",
      date: "2018-04-18",
      location: [Object],
      name: "FAMILY MARKET",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "63Oqek6ZELT55DeXza3ztPKXB0qYdrFaoLxKM",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 121,
      category: ["Shops", "Supermarkets and Groceries"],
      category_id: "22014000",
      date: "2018-04-18",
      location: [Object],
      name: "Metropolitan Transportation Authority",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "e4nYDejrX3HXXewQ6jk6i7MQaOyj1dudJ1E5j",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: -669.8,
      category: ["Shops", "Supermarkets and Groceries"],
      category_id: "21005000",
      date: "2018-04-18",
      location: [Object],
      name: "Payment Thank You-Mobile",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "drQYLe0XB3too7QewYKwCJvQr1z9VbFb3jepP",
      transaction_type: "special"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 669.8,
      category: ["Shops", "Supermarkets and Groceries"],
      category_id: "16001000",
      date: "2018-04-18",
      location: [Object],
      name: "Payment to Chase card ending in 8623 04/18",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "7yMBxAL3D9Ipp1KQP6yPIgdXPwmrOYCQjqmRL",
      transaction_type: "special"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 12,
      category: ["Shops", "Supermarkets and Groceries"],
      category_id: "21010001",
      date: "2018-04-18",
      location: [Object],
      name: "Venmo",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "8KE3xvDgyQImmo5ZpeXpFXaA017ZKNtyQ9az6",
      transaction_type: "special"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 38,
      category: ["Shops", "Supermarkets and Groceries"],
      category_id: "21010001",
      date: "2018-04-18",
      location: [Object],
      name: "Venmo",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "VLJYXVwR0rHJJrDPn8anFpMBzvVZojCrwLN83",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 39.84,
      category: ["Shops", "Supermarkets and Groceries"],
      category_id: "13005000",
      date: "2018-04-17",
      location: [Object],
      name: "SEAMLSSPELICANACHICKE",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "mb6Yke5RP9fyye3azrOzH0VYbQJ7xMCMDyxYD",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 70.36,
      category: ["Food and Drink", "Restaurants"],
      category_id: "19025000",
      date: "2018-04-16",
      location: [Object],
      name: "A TIME FOR WINE TROPICANA",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "Ym5YXVD436i55xZbrgOrt0Mg4ojOdACQx3BgN",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 62.65,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-04-16",
      location: [Object],
      name: "DOCK'S OYSTER HOUSE",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "zw0KaeDy7mubby8z9qM9uj1d54ogKOtOZ39qL",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 32.67,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-04-16",
      location: [Object],
      name: "P.F. Chang's China Bistro",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "e4nYDejrX3HXXewQ6jk6i7MQaOyj1dudJ1E51",
      transaction_type: "place"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 70,
      category: ["Food and Drink", "Restaurants"],
      category_id: "21010001",
      date: "2018-04-16",
      location: [Object],
      name: "Venmo",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "gxXYPe4mpyfggeLwjpvjUn4LbrdEPqCqLD1OJ",
      transaction_type: "special"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 300.99,
      category: ["Food and Drink", "Restaurants"],
      category_id: "21010001",
      date: "2018-04-16",
      location: [Object],
      name: "Venmo",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "b0EYweAr4bCEEVekQ7OQCe18YZrB3qFqwm7L0",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 50.65,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-04-16",
      location: [Object],
      name: "YAKITORI TOTTO",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "NEAO3Vb4qMsAAP4DOXKOFE6dQexN9rFRJra0n",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 2.5,
      category: ["Food and Drink", "Restaurants"],
      category_id: "22007000",
      date: "2018-04-15",
      location: [Object],
      name: "GREYHOUND F/S #2007",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "X1ZYXOL7RwuZZbawRAJRCjNyAq4vgat4w8mkk",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: -130.43,
      category: ["Bank Fees", "Foreign Transaction"],
      category_id: "18021000",
      date: "2018-04-13",
      location: [Object],
      name: "MEALPAL",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "p91wxegoPacAAeQNqVMqFnAeZO05wJCJ1jknm",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 13.07,
      category: ["Bank Fees", "Foreign Transaction"],
      category_id: "13005000",
      date: "2018-04-11",
      location: [Object],
      name: "OBAO",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "QnjYkV9yOxUjjJm9P5vPTaP9ZQo3k4uEDjmeM",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 25,
      category: ["Bank Fees", "Foreign Transaction"],
      category_id: "13005043",
      date: "2018-04-11",
      location: [Object],
      name: "Starbucks",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "ngLYAeo5a9FrreyXz5MzId8y1J4wYAtAn4eJa",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 20,
      category: ["Bank Fees", "Foreign Transaction"],
      category_id: "18045000",
      date: "2018-04-10",
      location: [Object],
      name: "PAYGATE_KIWDISK 4552788",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "RprYAEV7mOfrr3yzeApeIjZDz6xg0qtyQRD51",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 21.51,
      category: ["Bank Fees", "Foreign Transaction"],
      category_id: "13005000",
      date: "2018-04-09",
      location: [Object],
      name: "DISTRICT MOT.",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "MMkVBYm95xukkOwv6Qy6IzKaJw84bpIMeV3qB",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 13.66,
      category: ["Shops", "Food and Beverage Store"],
      category_id: "19047000",
      date: "2018-04-09",
      location: [Object],
      name: "FAMILY MARKET",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "E5D8dgrXBkHDD1xZEB6EsXM756ajJntpkaBv5",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 45.1,
      category: ["Shops", "Food and Beverage Store"],
      category_id: "13005000",
      date: "2018-04-09",
      location: [Object],
      name: "KONDO RESTAURANT",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "ORvYyVgZbPtvvQaNMmkMC9OND7ELqgI8a3KDV",
      transaction_type: "place"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 2.5,
      category: ["Shops", "Food and Beverage Store"],
      category_id: "10002000",
      date: "2018-04-09",
      location: [Object],
      name: "NON-CHASE ATM FEE-WITH",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "5BVPnKwqj6FZZbr4E1BECJaBbDxVqZFB9KkRk",
      transaction_type: "special"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 51.75,
      category: ["Shops", "Food and Beverage Store"],
      category_id: "21012002",
      date: "2018-04-09",
      location: [Object],
      name: "NON-CHASE ATM WITHDRAW 079564 04/082523 BROA",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "o7Ddreb590svv7KV4gE4CygODPEVbBFBZPjM8",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 33.81,
      category: ["Transfer", "Third Party", "Square"],
      category_id: "13005000",
      date: "2018-04-09",
      location: [Object],
      name: "SEAMLSSPELICANACHICKE",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "wnkBRYwm7gUvvqay48M4CbDQeZa5BoCL6oYqv",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 9.42,
      category: ["Transfer", "Third Party", "Square"],
      category_id: "13005000",
      date: "2018-04-08",
      location: [Object],
      name: "Chipotle Mexican Grill",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "mb6Yke5RP9fyye3azrOzH0VYbQJ7xMCMDyxJB",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 98,
      category: ["Transfer", "Third Party", "Square"],
      category_id: "22007000",
      date: "2018-04-08",
      location: [Object],
      name: "GREYHOUND LINES CNP",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "zw0KaeDy7mubby8z9qM9uj1d54ogKOtOZ39qO",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 12.4,
      category: ["Transfer", "Third Party", "Square"],
      category_id: "13005000",
      date: "2018-04-08",
      location: [Object],
      name: "McDonald's",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "drQYLe0XB3too7QewYKwCJvQr1z9VbFb3jeVo",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 9.5,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-04-06",
      location: [Object],
      name: "JUSTINO`S PIZZERIA",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "wnkBRYwm7gUvvqay48M4CbDQeZa5BoCL6oYX9",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 7.8,
      category: ["Food and Drink", "Restaurants"],
      category_id: "22016000",
      date: "2018-04-05",
      location: [Object],
      name: "TAXI SVC LONG ISALND C",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "Ym5YXVD436i55xZbrgOrt0Mg4ojOdACQx3Bge",
      transaction_type: "special"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 40,
      category: ["Food and Drink", "Restaurants"],
      category_id: "21012002",
      date: "2018-04-04",
      location: [Object],
      name: "ATM WITHDRAWAL 003555 04/0445 WALL S",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "9kRyx01QdPUggNv0nOknUVN01XvybqFdDKbRE",
      transaction_type: "special"
    },
    {
      account_id: "BJwax5vY6kFww0qQ9aJ9C4LnJab5zkf9qkYaP",
      account_owner: null,
      amount: -0.01,
      category: ["Food and Drink", "Restaurants"],
      category_id: "15001000",
      date: "2018-04-04",
      location: [Object],
      name: "INTEREST PAYMENT",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "ZqoYXV149LcooB04eOweCwgxk7ND9KFRJx67M",
      transaction_type: "special"
    },
    {
      account_id: "BJwax5vY6kFww0qQ9aJ9C4LnJab5zkf9qkYaP",
      account_owner: null,
      amount: 5,
      category: ["Food and Drink", "Restaurants"],
      category_id: "10000000",
      date: "2018-04-04",
      location: [Object],
      name: "MONTHLY SERVICE FEE",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "8KE3xvDgyQImmo5ZpeXpFXaA017ZKNtyQ9aro",
      transaction_type: "special"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 6,
      category: ["Food and Drink", "Restaurants"],
      category_id: "10000000",
      date: "2018-04-04",
      location: [Object],
      name: "MONTHLY SERVICE FEE",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "ZqoYXV149LcooB04eOweCwgxk7ND9KFRJx6EA",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 24.69,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-04-03",
      location: [Object],
      name: "LAN LARB",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "avMYdpkrPAFMMmZOneBnCN6brVvBM8UZYe8ym",
      transaction_type: "place"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 8.84,
      category: ["Food and Drink", "Restaurants"],
      category_id: "22006001",
      date: "2018-04-03",
      location: [Object],
      name: "Lyft",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "Axd48ZAnvJfddg6vkexkcqpOyKV8YMS6g07wb",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 130.43,
      category: ["Payment", "Credit Card"],
      category_id: "18021000",
      date: "2018-04-03",
      location: [Object],
      name: "MEALPAL",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "4q91nydP0wc88Rb604q0H6p570oE1mFkNQX1a",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 9.3,
      category: ["Payment", "Credit Card"],
      category_id: "22016000",
      date: "2018-04-03",
      location: [Object],
      name: "TAXI SVC 41-25 36TH ST",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "xpA3re65Rgf11VxnaXMaFp5o3RJqvQCMrveA5",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 15.66,
      category: ["Payment", "Credit Card"],
      category_id: "17001000",
      date: "2018-04-02",
      location: [Object],
      name: "UA KAUFMAN ASTORIA 14",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "rOqLre956EcrrBQP9gM9Im73L4pZD5cBE8vKx",
      transaction_type: "place"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 725,
      category: ["Payment", "Credit Card"],
      category_id: "21010001",
      date: "2018-04-02",
      location: [Object],
      name: "Venmo",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "k5dYye8RrNH00Yqd9g49TPq5pr1o67HRwBqbv",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 36,
      category: ["Payment", "Credit Card"],
      category_id: "17001000",
      date: "2018-04-01",
      location: [Object],
      name: "Regal Cinemas",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "vQKqgedkRPsppPQ67DM7IP9JqEwoY7HmNjQYd",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 5.54,
      category: ["Payment", "Credit Card"],
      category_id: "19047000",
      date: "2018-04-01",
      location: [Object],
      name: "TRADE FAIR #7",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "jZYz3mJR8MILL9PBzMrzCz7JkOoR8NUROXLQP",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 25.02,
      category: ["Transfer", "Third Party", "Venmo"],
      category_id: "19047000",
      date: "2018-04-01",
      location: [Object],
      name: "TRADE FAIR #7",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "0LownP96ZgH44v6kMnLMhqz1b3XaKnSr8abxQ",
      transaction_type: "place"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 40,
      category: ["Transfer", "Third Party", "Venmo"],
      category_id: "21012002",
      date: "2018-03-30",
      location: [Object],
      name: "ATM WITHDRAWAL 003609 03/3055 WATER",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "ydvy4eL5m0I11oJx6jM6FqKXyo0PJnSO1x4Rp",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 25.49,
      category: ["Transfer", "Third Party", "Venmo"],
      category_id: "19047000",
      date: "2018-03-30",
      location: [Object],
      name: "FAMILY MARKET",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "Axd48ZAnvJfddg6vkexkcqpOyKV8YMS6g07ZP",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: -653.23,
      category: ["Transfer", "Third Party", "Venmo"],
      category_id: "21005000",
      date: "2018-03-30",
      location: [Object],
      name: "Payment Thank You-Mobile",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "k5dYye8RrNH00Yqd9g49TPq5pr1o67HRwBqpX",
      transaction_type: "special"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 653.23,
      category: ["Transfer", "Third Party", "Venmo"],
      category_id: "16001000",
      date: "2018-03-30",
      location: [Object],
      name: "Payment to Chase card ending in 8623 03/30",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "KVy7PXZMDxUyyEQgd5pdHA5aBpow8ZcQY7pyy",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 149.55,
      category: ["Transfer", "Third Party", "Venmo"],
      category_id: "18063000",
      date: "2018-03-29",
      location: [Object],
      name: "TEXT2PAY",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "KVy7PXZMDxUyyEQgd5pdHA5aBpow8ZcQY7pLo",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 8.7,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-03-28",
      location: [Object],
      name: "CAFE ARTE 2",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "ydvy4eL5m0I11oJx6jM6FqKXyo0PJnSO1x4DZ",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 9.8,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-03-28",
      location: [Object],
      name: "KING OF FALAFEL & SHA",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "3P7Dn3M1gdUJJ48bzBPzF1kb9mK43wsKZB9zk",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 26.01,
      category: ["Food and Drink", "Restaurants"],
      category_id: "19047000",
      date: "2018-03-27",
      location: [Object],
      name: "FAMILY MARKET",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "qVP6re7OaqU117QvYKMYFvzp65krPefJZvbxQ",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 6.48,
      category: ["Food and Drink", "Restaurants"],
      category_id: "19025000",
      date: "2018-03-27",
      location: [Object],
      name: "PINKBERRY 15049",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "BJwax5vY6kFww0qQ9aJ9C4LXAdnzbVf9qkA8B",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 25,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005043",
      date: "2018-03-27",
      location: [Object],
      name: "Starbucks",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "PQ0YKV7ExXs00KaeQBAQTEq5jeR8X9UmQ3ZaZ",
      transaction_type: "place"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 40,
      category: ["Food and Drink", "Restaurants"],
      category_id: "21012002",
      date: "2018-03-26",
      location: [Object],
      name: "ATM WITHDRAWAL 001230 03/2655 WATER",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "BJwax5vY6kFww0qQ9aJ9C4LXAdnzbVf9qkAv4",
      transaction_type: "special"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 12.92,
      category: ["Food and Drink", "Restaurants"],
      category_id: "22006001",
      date: "2018-03-26",
      location: [Object],
      name: "Lyft",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "3P7Dn3M1gdUJJ48bzBPzF1kb9mK43wsKZB9PK",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 52.64,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-03-26",
      location: [Object],
      name: "YAKITORI TOTTO",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "1Db6nqVLAgUaa05QM1DMC7ZBg4Ypn1CmB8Xop",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 15.78,
      category: ["Food and Drink", "Restaurants"],
      category_id: "19043000",
      date: "2018-03-25",
      location: [Object],
      name: "CVS",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "LOK9qV571xcKKYLow7pwHVKb3pxAzXH0K4pdL",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 5.17,
      category: ["Food and Drink", "Restaurants"],
      category_id: "19025000",
      date: "2018-03-25",
      location: [Object],
      name: "GONG CHA CHINATOWN",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "rOqLre956EcrrBQP9gM9Im73L4pZD5cBE8vKQ",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 16.2,
      category: ["Transfer", "Withdrawal", "ATM"],
      category_id: "13005000",
      date: "2018-03-25",
      location: [Object],
      name: "McDonald's",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "DZLJxbj5EmILLQbvqDwqCmJrEwoxqzcZv38z1",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 12.03,
      category: ["Transfer", "Withdrawal", "ATM"],
      category_id: "13005000",
      date: "2018-03-23",
      location: [Object],
      name: "Potbelly Sandwich Shop",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "0LownP96ZgH44v6kMnLMhqz1b3XaKnSr8abxO",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 39.03,
      category: ["Transfer", "Withdrawal", "ATM"],
      category_id: "13005000",
      date: "2018-03-23",
      location: [Object],
      name: "SEAMLSSENTHAICETHAIKI",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "jZYz3mJR8MILL9PBzMrzCz7JkOoR8NUROXLQq",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 42.95,
      category: ["Transfer", "Withdrawal", "ATM"],
      category_id: "13005000",
      date: "2018-03-22",
      location: [Object],
      name: "BONCHON ASTORIA",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "vQKqgedkRPsppPQ67DM7IP9JqEwoY7HmNjQYx",
      transaction_type: "place"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 13.9,
      category: ["Transfer", "Withdrawal", "ATM"],
      category_id: "22006001",
      date: "2018-03-21",
      location: [Object],
      name: "Lyft",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "qVP6re7OaqU117QvYKMYFvzp65krPefJZvb1a",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 3.54,
      category: ["Transfer", "Withdrawal", "ATM"],
      category_id: "13005043",
      date: "2018-03-21",
      location: [Object],
      name: "Starbucks",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "k5dYye8RrNH00Yqd9g49TPq5pr1o67HRwBqpx",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 4.84,
      category: ["Transfer", "Withdrawal", "ATM"],
      category_id: "13005043",
      date: "2018-03-21",
      location: [Object],
      name: "Starbucks",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "Axd48ZAnvJfddg6vkexkcqpOyKV8YMS6g07Zd",
      transaction_type: "place"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 500,
      category: ["Transfer", "Withdrawal", "ATM"],
      category_id: "21010001",
      date: "2018-03-21",
      location: [Object],
      name: "Venmo",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "PQ0YKV7ExXs00KaeQBAQTEq5jeR8X9UmQ3ZOd",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 14.4,
      category: ["Transfer", "Withdrawal", "ATM"],
      category_id: "19047000",
      date: "2018-03-19",
      location: [Object],
      name: "FAMILY MARKET",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "KVy7PXZMDxUyyEQgd5pdHA5aBpow8ZcQY7pLK",
      transaction_type: "place"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 1.06,
      category: ["Food and Drink", "Restaurants"],
      category_id: "22006001",
      date: "2018-03-19",
      location: [Object],
      name: "Lyft",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "DZLJxbj5EmILLQbvqDwqCmJrEwoxqzcZv38Xe",
      transaction_type: "special"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 18.16,
      category: ["Food and Drink", "Restaurants"],
      category_id: "22006001",
      date: "2018-03-19",
      location: [Object],
      name: "Lyft",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "1Db6nqVLAgUaa05QM1DMC7ZBg4Ypn1CmB8XYe",
      transaction_type: "special"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 2.5,
      category: ["Food and Drink", "Restaurants"],
      category_id: "10002000",
      date: "2018-03-19",
      location: [Object],
      name: "NON-CHASE ATM FEE-WITH",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "63Oqek6ZELT55DeXza3ztPK9d1p35LHaoL3AB",
      transaction_type: "special"
    },
    {
      account_id: "PQ0YKV7ExXs00KaeQBAQTEqR6YXV8aSmQ3ern",
      account_owner: null,
      amount: 51.75,
      category: ["Food and Drink", "Restaurants"],
      category_id: "21012002",
      date: "2018-03-19",
      location: [Object],
      name: "NON-CHASE ATM WITHDRAW 452611 03/192523 BROA",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "LOK9qV571xcKKYLow7pwHVKb3pxAzXH0K4pJk",
      transaction_type: "special"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 7.61,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-03-18",
      location: [Object],
      name: "COTTON GOURMET INC.",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "ydvy4eL5m0I11oJx6jM6FqKXyo0PJnSO1x4D1",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 61.17,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      date: "2018-03-18",
      location: [Object],
      name: "HAEIN SUSHI AND SASHIMI",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "3P7Dn3M1gdUJJ48bzBPzF1kb9mK43wsKZB97w",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 23.22,
      category: ["Food and Drink", "Restaurants"],
      category_id: "19047000",
      date: "2018-03-14",
      location: [Object],
      name: "TRADE FAIR #7",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "BJwax5vY6kFww0qQ9aJ9C4LXAdnzbVf9qkAdg",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 25.04,
      category: ["Shops", "Food and Beverage Store"],
      category_id: "13005000",
      date: "2018-03-13",
      location: [Object],
      name: "KING OF FALAFEL & SHA",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "1Db6nqVLAgUaa05QM1DMC7ZBg4Ypn1CmB8XjQ",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 121,
      category: ["Shops", "Food and Beverage Store"],
      category_id: "22014000",
      date: "2018-03-13",
      location: [Object],
      name: "Metropolitan Transportation Authority",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "qVP6re7OaqU117QvYKMYFvzp65krPefJZvbBv",
      transaction_type: "place"
    },
    {
      account_id: "qVP6re7OaqU117QvYKMYFvzk8VPLrxHJZvVoe",
      account_owner: null,
      amount: 30.22,
      category: ["Shops", "Food and Beverage Store"],
      category_id: "13005000",
      date: "2018-03-13",
      location: [Object],
      name: "SEAMLSSDISTRICTSAIGON",
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: "PQ0YKV7ExXs00KaeQBAQTEq5jeR8X9UmQ3Z1j",
      transaction_type: "place"
    }
  ]
};

module.exports = {
  demoAccounts,
  demoTransaction,
  phoneBill,
  rentBill
};
